from __future__ import annotations

from typing import Any

from domain.cockpit.ai_reasoning_adapter import build_ai_reasoning_context
from services.llm_adapter_service import LLMAdapterService


class StubLLMClient:
    def generate_reasoning(self, context: dict[str, Any]) -> dict[str, Any]:
        return {
            "status": "available",
            "summary": f"Reviewed {context['symbol']} with provided cockpit context.",
            "reasoning_points": ["Point generated by stub client."],
            "caveats": ["Stub output for contract test only."],
        }


class FailingLLMClient:
    def generate_reasoning(self, context: dict[str, Any]) -> dict[str, Any]:  # noqa: ARG002
        raise RuntimeError("provider offline")


def test_ai_reasoning_context_is_prepared_without_calling_llm() -> None:
    context = build_ai_reasoning_context(_cockpit_payload())

    assert context["symbol"] == "BTCUSD"
    assert context["timeframe"] == "H1"
    assert context["signal_decision"]["action"] == "BUY"
    assert "Do not claim certainty" in context["instruction"]


def test_llm_adapter_default_disabled_returns_template_reasoning() -> None:
    result = LLMAdapterService().explain(_cockpit_payload())

    assert result["status"] == "available"
    assert result["mode"] == "disabled"
    assert "deterministic template reasoning" in " ".join(result["caveats"])
    assert result["reasoning_points"]


def test_llm_adapter_local_mode_without_client_is_not_available() -> None:
    result = LLMAdapterService(mode="local").explain(_cockpit_payload())

    assert result["status"] == "not_available"
    assert result["mode"] == "local"
    assert "no local client" in " ".join(result["caveats"]).lower()


def test_llm_adapter_can_use_injected_local_client() -> None:
    result = LLMAdapterService(mode="local", local_client=StubLLMClient()).explain(_cockpit_payload())

    assert result["status"] == "available"
    assert result["mode"] == "local"
    assert result["summary"].startswith("Reviewed BTCUSD")


def test_llm_adapter_provider_failure_is_defensive() -> None:
    result = LLMAdapterService(mode="api", api_client=FailingLLMClient()).explain(_cockpit_payload())

    assert result["status"] == "not_available"
    assert result["mode"] == "api"
    assert "provider offline" in " ".join(result["caveats"])


def _cockpit_payload() -> dict[str, Any]:
    return {
        "symbol": "BTCUSD",
        "timeframe": "H1",
        "market_overview": {
            "status": "available",
            "signal": "BUY",
            "bias": "bullish",
            "risk_level": "medium",
        },
        "signal_decision": {"status": "available", "action": "BUY"},
        "risk_gate": {"status": "available", "risk_status": "allowed"},
        "data_quality": {"status": "available", "score": 92},
        "regime_analysis": {"status": "available", "regime": "trending"},
        "risk_plan": {"status": "available"},
        "multi_timeframe": {"status": "not_available"},
        "market_structure": {"status": "not_available"},
        "sentiment_context": {"status": "limited"},
        "backtest_snapshot": {"status": "not_available"},
        "evidence_layer": {"status": "available"},
    }

