create table if not exists public.analysis_logs (
  id bigint generated by default as identity primary key,
  symbol text not null,
  timeframe text not null,
  signal text not null,
  bias text not null,
  confidence double precision not null,
  summary text not null,
  raw_payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_analysis_logs_created_at on public.analysis_logs (created_at desc);
create index if not exists idx_analysis_logs_symbol_timeframe on public.analysis_logs (symbol, timeframe);

create table if not exists public.watchlists (
  id bigint generated by default as identity primary key,
  symbol text not null,
  market_type text not null,
  notes text not null default '',
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_watchlists_created_at on public.watchlists (created_at desc);
create index if not exists idx_watchlists_symbol on public.watchlists (symbol);

