do $$
begin
  create type public.user_tier as enum ('free', 'plus', 'pro');
exception
  when duplicate_object then null;
end $$;

alter table public.analysis_logs
  add column if not exists user_id uuid references auth.users (id) on delete set null;

alter table public.watchlists
  add column if not exists user_id uuid references auth.users (id) on delete set null;

create index if not exists idx_analysis_logs_user_created_at
  on public.analysis_logs (user_id, created_at desc);

create index if not exists idx_watchlists_user_created_at
  on public.watchlists (user_id, created_at desc);

create table if not exists public.user_profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  email text not null unique,
  display_name text not null default '',
  tier public.user_tier not null default 'free',
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.tier_limits (
  tier public.user_tier primary key,
  daily_analysis_limit integer not null,
  watchlist_limit integer not null,
  cockpit_enabled boolean not null default true,
  advanced_risk_enabled boolean not null default false,
  notes text not null default ''
);

insert into public.tier_limits (
  tier,
  daily_analysis_limit,
  watchlist_limit,
  cockpit_enabled,
  advanced_risk_enabled,
  notes
) values
  ('free', 40, 20, true, false, 'Entry tier for exploration and learning workflow'),
  ('plus', 160, 80, true, true, 'Intermediate tier with higher limits and advanced risk support'),
  ('pro', 600, 300, true, true, 'Professional tier for high-frequency workflow')
on conflict (tier)
do update
set
  daily_analysis_limit = excluded.daily_analysis_limit,
  watchlist_limit = excluded.watchlist_limit,
  cockpit_enabled = excluded.cockpit_enabled,
  advanced_risk_enabled = excluded.advanced_risk_enabled,
  notes = excluded.notes;

create table if not exists public.user_usage_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  event_type text not null,
  context jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_user_usage_events_user_created_at
  on public.user_usage_events (user_id, created_at desc);

create index if not exists idx_user_usage_events_type_created_at
  on public.user_usage_events (event_type, created_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists trg_user_profiles_set_updated_at on public.user_profiles;
create trigger trg_user_profiles_set_updated_at
before update on public.user_profiles
for each row
execute procedure public.set_updated_at();

alter table public.analysis_logs enable row level security;
alter table public.watchlists enable row level security;
alter table public.user_profiles enable row level security;
alter table public.tier_limits enable row level security;
alter table public.user_usage_events enable row level security;

drop policy if exists "analysis_logs_select_own" on public.analysis_logs;
create policy "analysis_logs_select_own"
on public.analysis_logs
for select
to authenticated
using ((select auth.uid()) is not null and user_id = (select auth.uid()));

drop policy if exists "analysis_logs_insert_own" on public.analysis_logs;
create policy "analysis_logs_insert_own"
on public.analysis_logs
for insert
to authenticated
with check ((select auth.uid()) is not null and user_id = (select auth.uid()));

drop policy if exists "analysis_logs_update_own" on public.analysis_logs;
create policy "analysis_logs_update_own"
on public.analysis_logs
for update
to authenticated
using ((select auth.uid()) is not null and user_id = (select auth.uid()))
with check ((select auth.uid()) is not null and user_id = (select auth.uid()));

drop policy if exists "analysis_logs_delete_own" on public.analysis_logs;
create policy "analysis_logs_delete_own"
on public.analysis_logs
for delete
to authenticated
using ((select auth.uid()) is not null and user_id = (select auth.uid()));

drop policy if exists "watchlists_select_own" on public.watchlists;
create policy "watchlists_select_own"
on public.watchlists
for select
to authenticated
using ((select auth.uid()) is not null and user_id = (select auth.uid()));

drop policy if exists "watchlists_insert_own" on public.watchlists;
create policy "watchlists_insert_own"
on public.watchlists
for insert
to authenticated
with check ((select auth.uid()) is not null and user_id = (select auth.uid()));

drop policy if exists "watchlists_update_own" on public.watchlists;
create policy "watchlists_update_own"
on public.watchlists
for update
to authenticated
using ((select auth.uid()) is not null and user_id = (select auth.uid()))
with check ((select auth.uid()) is not null and user_id = (select auth.uid()));

drop policy if exists "watchlists_delete_own" on public.watchlists;
create policy "watchlists_delete_own"
on public.watchlists
for delete
to authenticated
using ((select auth.uid()) is not null and user_id = (select auth.uid()));

drop policy if exists "user_profiles_select_own" on public.user_profiles;
create policy "user_profiles_select_own"
on public.user_profiles
for select
to authenticated
using ((select auth.uid()) is not null and id = (select auth.uid()));

drop policy if exists "user_profiles_insert_own" on public.user_profiles;
create policy "user_profiles_insert_own"
on public.user_profiles
for insert
to authenticated
with check ((select auth.uid()) is not null and id = (select auth.uid()));

drop policy if exists "user_profiles_update_own" on public.user_profiles;
create policy "user_profiles_update_own"
on public.user_profiles
for update
to authenticated
using ((select auth.uid()) is not null and id = (select auth.uid()))
with check ((select auth.uid()) is not null and id = (select auth.uid()));

drop policy if exists "tier_limits_read_all" on public.tier_limits;
create policy "tier_limits_read_all"
on public.tier_limits
for select
to authenticated, anon
using (true);

drop policy if exists "user_usage_events_select_own" on public.user_usage_events;
create policy "user_usage_events_select_own"
on public.user_usage_events
for select
to authenticated
using ((select auth.uid()) is not null and user_id = (select auth.uid()));

drop policy if exists "user_usage_events_insert_own" on public.user_usage_events;
create policy "user_usage_events_insert_own"
on public.user_usage_events
for insert
to authenticated
with check ((select auth.uid()) is not null and user_id = (select auth.uid()));

grant usage on schema public to anon, authenticated;
grant select on public.tier_limits to anon, authenticated;
grant select, insert, update, delete on public.analysis_logs to authenticated;
grant select, insert, update, delete on public.watchlists to authenticated;
grant select, insert, update on public.user_profiles to authenticated;
grant select, insert on public.user_usage_events to authenticated;
